# Generated by Django 2.1.5 on 2019-01-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigilancia', models.BooleanField(blank=True, null=True)),
                ('parqueadero', models.BooleanField(blank=True, null=True)),
                ('salon_social', models.BooleanField(blank=True, null=True)),
                ('numero_pisos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('ext', models.ForeignKey(on_delete='CASCADE', to='houses.exterior')),
                ('gen', models.ForeignKey(on_delete='CASCADE', to='houses.general')),
            ],
            options={
                'ordering': ['tipo', 'subtipo'],
            },
        ),
        migrations.CreateModel(
            name='interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuartos', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('closets', models.IntegerField()),
                ('calentador', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='inte',
            field=models.ForeignKey(on_delete='CASCADE', to='houses.interior'),
        ),
    ]
